In [1]:
import numpy as np

In [2]:
# !pip install numpy

In [3]:
my_list = [10,20,30,40]

In [4]:
type(my_list)

list

In [5]:
np.array(my_list)

array([10, 20, 30, 40])

In [7]:
my_numpy_array = np.array([10,20,30,40,50])

In [8]:
type(my_numpy_array)

numpy.ndarray

In [9]:
my_numpy_array.max()

50

In [10]:
# https://jalammar.github.io/visual-numpy/

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.random.random(5)

array([0.92592341, 0.22830596, 0.30502652, 0.8765612 , 0.98434607])

In [14]:
#array arithmetic 

In [15]:
my_list1 = [1,2]

In [16]:
my_list2 = [2,3]

In [17]:
my_list1 + my_list2

[1, 2, 2, 3]

In [18]:
my_numpy_array1 = np.array(my_list1)

In [19]:
my_numpy_array2 = np.array(my_list2)

In [20]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [21]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [22]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [23]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [24]:
my_numpy_array1 * 5

array([ 5, 10])

In [36]:
other_array = np.array([10,20,30,40,50])

In [39]:
other_array.min()

10

In [38]:
other_array.sum()

150

In [26]:
#indexing & arange

In [26]:
#indexing & arange

In [27]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
np_array = np.arange(0,10)

In [31]:
np_array[0]

0

In [32]:
np_array[-1]

9

In [33]:
np_array[1:4:]

array([1, 2, 3])

In [34]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [35]:
np_array[2:6:2]

array([2, 4])

In [40]:
# random

In [41]:
np.random.randn(4)

array([-1.01630674, -1.09829885,  0.70948785,  2.54035352])

In [42]:
np.random.randn(4,4) #we will see matrices in details

array([[-1.92619892,  0.6432985 ,  1.52906877, -0.45387039],
       [ 1.09507191, -1.56907651, -0.0185524 ,  0.21799423],
       [-0.8186812 , -1.12639982, -1.59773834,  0.36370991],
       [ 0.71767334,  0.64516878, -0.37454103,  0.50293794]])

In [43]:
np.random.randint(1,300,5)

array([ 89, 169, 249,  29, 161])