In [1]:
import numpy as np

In [7]:
my_matrix = [[5,10],[15,20]]

In [8]:
my_matrix[0]

[5, 10]

In [9]:
my_matrix[1]

[15, 20]

In [12]:
#my_matrix.sum()

In [10]:
numpy_matrix = np.array([[5,10],[15,20]])

In [13]:
numpy_matrix.sum()

50

In [20]:
# row x column

In [21]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.random.random((3,2))

array([[0.16776112, 0.00703872],
       [0.00533717, 0.89356651],
       [0.11160896, 0.6911002 ]])

In [24]:
# matrix arithmetic 

In [25]:
first_array = np.array([[10,20],[30,40]])

In [26]:
second_array = np.array([[5,15],[25,35]])

In [27]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [28]:
first_array * 2

array([[20, 40],
       [60, 80]])

In [29]:
first_array / 4

array([[ 2.5,  5. ],
       [ 7.5, 10. ]])

In [30]:
# We can add and multiply matrices using arithmetic operators (+-*/) if the two matrices are the same size.

In [31]:
third_array = np.array([[10],[20]])

In [32]:
third_array

array([[10],
       [20]])

In [34]:
third_array.shape

(2, 1)

In [35]:
first_array.shape

(2, 2)

In [39]:
first_array

array([[10, 20],
       [30, 40]])

In [36]:
first_array + third_array

array([[20, 30],
       [50, 60]])

In [38]:
# We do these arithmetic operations on matrices of different size only if the different dimension is one 
#in which case NumPy uses its broadcast rules for that operation:

In [40]:
fourth_array = np.ones((3,4))

In [41]:
fourth_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
#fourth_array + first_array

In [44]:
# matrix multiplication

In [45]:
first_matrix = np.array([[10,20,30]])

In [46]:
first_matrix

array([[10, 20, 30]])

In [48]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [49]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [50]:
first_matrix.shape

(1, 3)

In [51]:
second_matrix.shape

(3, 2)

In [53]:
#first_matrix * second_matrix

In [55]:
result_matrix = first_matrix.dot(second_matrix)

In [56]:
result_matrix

array([[120, 180]])

In [57]:
result_matrix.shape

(1, 2)