In [1]:
import numpy as np

In [2]:
new_array = np.random.randint(1,100,20)

In [3]:
new_array

array([37, 64, 64, 69, 81, 36, 23, 62, 10, 95, 40, 83, 59, 76, 28, 19,  7,
       81, 61, 47])

In [4]:
new_array > 25

array([ True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True])

In [5]:
new_array[new_array > 25]

array([37, 64, 64, 69, 81, 36, 62, 95, 40, 83, 59, 76, 28, 81, 61, 47])

In [6]:
#transpose & reshape

In [7]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [8]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [9]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [10]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [11]:
random_array = np.random.random((6,1))

In [12]:
random_array

array([[0.24590505],
       [0.82413243],
       [0.57636962],
       [0.03514044],
       [0.87443472],
       [0.97933209]])

In [13]:
random_array.reshape(2,3)

array([[0.24590505, 0.82413243, 0.57636962],
       [0.03514044, 0.87443472, 0.97933209]])

In [14]:
random_array.reshape(3,2)

array([[0.24590505, 0.82413243],
       [0.57636962, 0.03514044],
       [0.87443472, 0.97933209]])

In [15]:
# real life cases

In [16]:
data = np.array([10, 12, 13, 15, 18, 25, 100, 105])

In [17]:
# Compute Z-scores
mean = np.mean(data)

In [33]:
mean

37.25

In [18]:
std = np.std(data)

In [34]:
std

37.9333296719389

In [19]:
z_scores = (data - mean) / std

In [20]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [27]:
np.abs(z_scores) > 1

array([False, False, False, False, False, False,  True,  True])

In [31]:
outliers = data[np.abs(z_scores) > 1]

In [32]:
outliers

array([100, 105])

In [35]:
# math equations

In [36]:
# Solve 2x + 3y = 8 and 5x + 7y = 19

In [37]:
# Coefficients matrix
A = np.array([[2, 3], [5, 7]])

In [38]:
# Constants matrix
b = np.array([8, 19])

In [39]:
# Solve for x and y
solution = np.linalg.solve(A, b)

In [40]:
solution

array([1., 2.])

In [41]:
# data analysis

In [42]:
# Stock prices over 5 days
prices = np.array([100, 102, 105, 107, 110])

In [48]:
np.diff(prices)

array([2, 3, 2, 3])

In [51]:
prices[:len(prices)-1:]

array([100, 102, 105, 107])

In [52]:
prices[:-1:]

array([100, 102, 105, 107])

In [53]:
np.diff(prices) / prices[:-1]

array([0.02      , 0.02941176, 0.01904762, 0.02803738])

In [54]:
returns = np.diff(prices) / prices[:-1] * 100

In [55]:
returns

array([2.        , 2.94117647, 1.9047619 , 2.80373832])